import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

import { Jomolhari } from 'next/font/google'
import SessionWrapper from "@/components/SessionWrapper";

const Jomol = Jomolhari({
  weight: ['400'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Toy Universe",
  description: "Generated by create prev app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={Jomol.className}>
      <SessionWrapper>
        <body>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </SessionWrapper>
    </html>
  );
}
